CREATE TABLE  todoItems (todoID INT AUTO_INCREMENT PRIMARY KEY, todoItem VARCHAR(250) NOT NULL, todoDateAdded DATETIME DEFAULT NOW() NOT NULL, todoStatus BOOLEAN NOT NULL, todoDueBy DATETIME, projectID INT NOT NULL );

